// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNtdQXK_5gJg_OCPSkYd7x7jCj6-0uZY',
    appId: '1:881326400280:web:366ab7f3c870a415a0346d',
    messagingSenderId: '881326400280',
    projectId: 'resik-49c66',
    authDomain: 'resik-49c66.firebaseapp.com',
    storageBucket: 'resik-49c66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WdO2mwufAkwzlQTjuvPVuUec9r9FgrI',
    appId: '1:881326400280:android:cb0d1c0455fc6791a0346d',
    messagingSenderId: '881326400280',
    projectId: 'resik-49c66',
    storageBucket: 'resik-49c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6TWdEAcmd-QbaiizP99kvzKVr-8EoE00',
    appId: '1:881326400280:ios:bf554f02870c2ec7a0346d',
    messagingSenderId: '881326400280',
    projectId: 'resik-49c66',
    storageBucket: 'resik-49c66.firebasestorage.app',
    iosBundleId: 'com.example.resik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6TWdEAcmd-QbaiizP99kvzKVr-8EoE00',
    appId: '1:881326400280:ios:bf554f02870c2ec7a0346d',
    messagingSenderId: '881326400280',
    projectId: 'resik-49c66',
    storageBucket: 'resik-49c66.firebasestorage.app',
    iosBundleId: 'com.example.resik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvNtdQXK_5gJg_OCPSkYd7x7jCj6-0uZY',
    appId: '1:881326400280:web:e84c139760040c0ea0346d',
    messagingSenderId: '881326400280',
    projectId: 'resik-49c66',
    authDomain: 'resik-49c66.firebaseapp.com',
    storageBucket: 'resik-49c66.firebasestorage.app',
  );
}
